#!/bin/sh

readonly scriptpath="$(readlink -f "$0")"
readonly workdir="${scriptpath%/*}"

update() {
	if [ -z "$1" ] || [ -z "$2" ]; then return 1; fi
	if [ -f "$1" ] && [ -r "$1" ] && ! [ -L "$1" ] && ! cmp --silent "$1" "$2"; then
		#echo ">>> Updating '$2' from '$1' ..."
		cat "$1" > "${workdir}/$2"
	else
		return 1
	fi
}

update ~/.xmodmap configs/DOTxmodmap
update ~/.config/user-dirs.dirs configs/user-dirs.dirs
update ~/.config/dunstrc configs/DOTconfig_dunstrc

git status --porcelain
