#!/bin/sh

readonly scriptpath="$(readlink -f "$0")"
readonly workdir="${scriptpath%/*}"

update() {
	if [ -z "$1" ] || [ -z "$2" ]; then return 1; fi
	if [ -f "$1" ] && [ -r "$1" ] && ! [ -L "$1" ] && ! cmp --silent "$1" "$2"; then
		#echo ">>> Updating '$2' from '$1' ..."
		cat "$1" > "${workdir}/$2"
	else
		return 1
	fi
}

update ~/.Xdefaults  configs/DOTXDefaults
update ~/.config/tint2/tint2rc configs/tint2rc
update ~/.vimrc configs/DOTvimrc
update ~/.compton.conf configs/DOTcompton.conf
update ~/.gitconfig configs/DOTgitconfig && sed -r 's#(name|email) =.*#\1 = NULL#g;' -i configs/DOTgitconfig
update ~/.mpv/config configs/DOTmpv_slash_config
update ~/.xmodmap configs/DOTxmodmap
update ~/.config/user-dirs.dirs configs/user-dirs.dirs
update ~/.config/dunstrc configs/DOTconfig_dunstrc

git status --porcelain
