#!/bin/bash
# lockscreen 0.1
# Alock wrapper, designed to work as normal user and as root, executed by for example actkbd or acpid.
###
# Copyright (c) 2011, Piotr Karbowski <piotr.karbowski@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, are
# permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice, this
#   list of conditions and the following disclaimer in the documentation and/or other
#   materials provided with the distribution.
# * Neither the name of the Piotr Karbowski nor the names of its contributors may be
#   used to endorse or promote products derived from this software without specific
#   prior written permission.

# todo: do lock, don't run alock twice.

eerror() { echo -e "\033[1;31m>>> \033[0m$@"; }
einfo() { echo -e "\033[1;32m>>> \033[0m$@"; }

if [ "${UID}" = '0' ]; then
	export DISPLAY=':0'

	# Get username of user who started xserver.
	xsession_username=( $(ps --no-headers -C 'xinit' -o '%u') )
	if [ "${#xsession_username[@]}" -gt '1' ]; then
		eerror "The xinit process is executed more than once. Multiple Xserver sessions?"; exit 1
	elif [ "${#xsession_username[@]}" != '1' ]; then
		eerror "No xinit found, either there is no Xserver running or you are using graphical login manager."; exit 1
	fi

	homedir="$(sed -r '\#^'"${xsession_username}:"'#!d; s#(.*):(.*):(.*):(.*):(.*):(.*):(.*)$#\6#g' /etc/passwd)"
	if [ "$?" != '0' ]; then
		eerror "Unable to get ${xsession_username}'s home dir path."; exit 1
	fi
else
	export DISPLAY="${DISPLAY:-:0}"
	xsession_username="$USER"
	homedir="$HOME"
fi

if ! [ -f "${homedir}/.alock.passwd" ]; then
	eerror "Create '${homedir}/.alock.passwd' file with sha512-hash of password for unlocking screen."
	eerror "Example: echo -n 'password' | sha512sum | cut -c -128"
	exit 1
fi

if ! [ -f "${homedir}/.alock.image" ]; then
	eerror "Symlink to or create '${homedir}/.alock.image' with the image you want to display when screen is locked."
	eerror "Example: ln -s ~/wallpapers/whatever.png ~/.alock.image"
	exit 1
fi

# Command as variable instead of function, easier to execute via su.
lockscreen_cmd="alock -auth sha512:file=${homedir}/.alock.passwd -bg image:file=${homedir}/.alock.image"

if [ "${UID}" = '0' ]; then
	su - "${xsession_username}" -c "${lockscreen_cmd}" || eerror "su or alock failed."; exit 1
else
	${lockscreen_cmd} || eerror "alock failed."; exit 1
fi
