#!/bin/sh

umask 077

# Awk of choice.
awk='mawk'

acpistat_cache="${HOME}/tmp/acpistat.cache"
if [ -f "${acpistat_cache}" ]; then
	. "${acpistat_cache}"
else
	for i in /sys/class/power_supply/*; do
		[ -f "${i}/type" ] && dev_type="$(cat "${i}/type")"
		[ -n "${dev_type}" ] || return
		if [ "${dev_type}" = 'Mains' ]; then
			ac_adapter_dir="${i}"
		elif [ "${dev_type}" = 'Battery' ]; then
			battery_dir="${i}"
		fi
	done
	printf 'ac_adapter_dir="%s"\nbattery_dir="%s"\n' "${ac_adapter_dir}" "${battery_dir}" >"${acpistat_cache}"
fi

exec ${awk} -v battery_dir="${battery_dir}" -v ac_adapter_dir="${ac_adapter_dir}"  -f - <<-'_awk_code'
function hms(s) {
	h=int(s/3600);
	s=s-(h*3600);
	m=int(s/60);
	s=s-(m*60);
	output = sprintf("%d:%02d:%02d", h, m, s);
	return(output)
}
BEGIN {
	getline ac_status < ( ac_adapter_dir "/online" )
	getline battery_status < ( battery_dir "/status" )
	getline battery_remaining < ( battery_dir "/charge_now" )
	getline battery_total < ( battery_dir "/charge_full" )
	getline battery_usage_now < ( battery_dir "/current_now" )
	battery_percent = int((battery_remaining*100)/(battery_total))
	if (battery_percent > 100) battery_percent = 100
	if (ac_status) {
		print "AC on-line", ( (battery_status == "Full") ? "Charged" : battery_status ) ", " battery_percent "%"
	} else {
		print "AC off-line", battery_status ", " battery_percent "%, " hms(3600*(battery_remaining/battery_usage_now))
	}
}
_awk_code
