#!/bin/sh
# Choose USB DAC as default alsa device, if connected.

asoundrc="${HOME}/.asoundrc"

cat >"${asoundrc}" <<EOF
pcm.usbdac {
	type dmix
	ipc_key 1024
	slave {
		pcm "hw:DAC"
		rate 44100
	}
}

pcm.usbdac_nodmix {
	type hw
	card DAC
}
EOF

if aplay -l | grep -qE '^card .*\[USB Audio DAC\]'; then
	echo 'pcm.!default usbdac_nodmix' >>"${asoundrc}"
fi

