#!/bin/bash

# Geenrate ~/.asoundrc with specified card as default.

dmenu_wrapper() {
    # A magic to position dmenu in the middle of screen.
    read screen_w screen_h < <( xdpyinfo | sed -r '/dimensions:/!d; s/.*dimensions:[[:blank:]]+([0-9]+)x([0-9]+) pixels.*/\1 \2/')
    dmenu_width='500'
    pull_up='140'
    x_offset="$(( (screen_w - dmenu_width) / 2 ))"
    y_offset="$(( (screen_h - pull_up) / 2 ))"

    dmenu -i -l 10 \
        -y "${y_offset}" -x "${x_offset}" -w "${dmenu_width}" \
        -fn 'Droid Sans Mono:pixelsize=15'  \
        -sb '#a13d12' \
        -p "$*"
}

for i in dmenu; do
    if ! command -v "$i" >/dev/null 2>&1; then
        die "Missing binary '$i'."
    fi
done

cards() {
    awk -f - /proc/asound/cards <<-'END'
		/^ *[0-9]+/ {
		    card = $1;
			sub(/.*- /, "")
			printf("%s %128s\n", $0, card)
		}
	END
}


read dmenu_selection < <(dmenu_wrapper 'Set default ALSA device to:' < <(cards))
dmenu_selection="${dmenu_selection##* }"

if ! [ "${dmenu_selection}" ]; then
	exit 0
fi

cat > ~/.asoundrc <<EOF
defaults.pcm.!card ${dmenu_selection}; 
defaults.ctl.!card ${dmenu_selection};
EOF
