#!/bin/bash

# Toggle Synaptics Touchpad.

dmenu_wrapper() {
    dmenu -b -i -l 10 \
        -fn 'Droid Sans Mono:pixelsize=15'  \
        -p "$*"
}

for i in dmenu; do
    if ! command -v "$i" >/dev/null 2>&1; then
        die "Missing binary '$i'."
    fi
done

eval $(synclient -l | awk '/TouchpadOff/ { gsub(/ /, ""); print }')

case "${TouchpadOff}" in
    1)
        prompt="disabled"
    ;;
    0)
        prompt="enabled"
    ;;
    *)
        echo "Something went wrong."
        exit 1
    ;;
esac

read dmenu_selection _ < <(dmenu_wrapper "Toggle touchpad [${prompt}]" < <(printf "%s\n" 'Enable' 'Disable'))

if ! [ "${dmenu_selection}" ]; then
	exit 0
fi

case "${dmenu_selection}" in
    'Enable')
        synclient TouchpadOff=0
    ;;
    'Disable')
        synclient TouchpadOff=1
    ;;
esac
