#!/bin/bash

# Geenrate ~/.asoundrc with specified card as default.

dmenu_wrapper() {
    dmenu -b -i -l 10 \
        -fn 'Droid Sans Mono:pixelsize=15'  \
        -p 'Select default ALSA card:'
}

for i in dmenu; do
    if ! command -v "$i" >/dev/null 2>&1; then
        die "Missing binary '$i'."
    fi
done

cards() {
    awk -f - /proc/asound/cards <<-'END'
		/^ *[0-9]+/ {
		    card = $1;
			sub(/.*- /, "")
			printf("%-2s %s\n", card, $0)
		}
	END
}


read dmenu_selection _ < <(dmenu_wrapper < <(cards))

if ! [ "${dmenu_selection}" ]; then
	exit 0
fi

cat > ~/.asoundrc <<EOF
defaults.pcm.!card ${dmenu_selection}; 
defaults.ctl.!card ${dmenu_selection};
EOF
