#!/bin/bash

# Jump to choosen window on any desktop.
# Work best when shell is configured to alter terminal title with executed commands.

eerror() {
    echo ">>> [ERROR] $*"
}

die() {
    eerror "$*"
    exit 1
}

dmenu_wrapper() {
    # A magic to position dmenu in the middle of screen.
    read screen_w screen_h < <( xdpyinfo | sed -r '/dimensions:/!d; s/.*dimensions:[[:blank:]]+([0-9]+)x([0-9]+) pixels.*/\1 \2/')
    dmenu_width='1000'
    pull_up='140'
    x_offset="$(( (screen_w - dmenu_width) / 2 ))"
    y_offset="$(( (screen_h - pull_up) / 2 ))"

    dmenu -i -l 10 \
        -y "${y_offset}" -x "${x_offset}" -w "${dmenu_width}" \
        -fn 'Droid Sans Mono:pixelsize=15'  \
        -sb '#a13d12' \
        -p "$*"
}

for i in wmctrl dmenu; do
    if ! command -v "$i" >/dev/null 2>&1; then
        die "Missing binary '$i'."
    fi
done

declare -a windows
while read id desktop wm_class hostname window_title; do
    if ! [ "${desktop}" -ge 0 ]; then
        # Skip non-windows (conky, tint2 etc)
        continue
    fi

    app_name="${wm_class##*.}"

    if [ "${#app_name}" -ge 20 ]; then
        app_name="${app_name:0:17}..."
    fi

    windows+=( "${window_title} - ${app_name} - ${id}" )

done < <(wmctrl -lx | sort -k 2)

read dmenu_selection < <(dmenu_wrapper 'Select window:' < <(printf '%s\n' "${windows[@]}"))
dmenu_selection="${dmenu_selection##* - }"

case "${dmenu_selection}" in
    '0x'*)
        wmctrl -ia "${dmenu_selection}"
    ;;
esac
