#!/usr/bin/env perl

# Smallish helper to help with ffmpeg automation to split files.

# Usage: ./duration.pl 00:40:25 01:45:18

use strict;
use warnings;

sub time_to_seconds {
    my ($h, $m, $s) = split(/:/, $_[0]);
    $s += $h * 60 * 60;
    $s += $m * 60;
    
    return $s;
}

sub duration {
    my ($start, $end) = @_;

    my $start_s = time_to_seconds($start);
    my $end_s = time_to_seconds($end);

    my $duration = $end_s - $start_s;

    printf("%02d:%02d:%02d\n", int($duration/60/60)%24, int($duration/60)%60, $duration%60)
}

die "Wrong arguments!\n" if not scalar @ARGV == 2;

duration($ARGV[0], $ARGV[1]);
