#!/bin/bash

# set env var video_player if anything other than mpv.
video_player="${video_player:-mpv}"

# Example usage:
#   To play random AMV on full screen: cd video/amv && mprand --fs
#   Just to play music from random AMVs: cd video/amv && mpvrand --ao null

command -v "${video_player}" 2>/dev/null || { echo "Wrong video_player variable."; exit 1; }

while true; do
	IFS=$'\n'
	for i in $(find -L "$PWD"/ -type f | sort -R); do
        shopt -s nocasematch;
        if [[ "$i" =~ \.(jpeg|jpg|png|gif)$ ]]; then continue; fi
		"${video_player}" "$i" "$@"
		sleep 0.3
	done
	sleep 0.3
done
