#!/usr/bin/env perl

# TODO: conver special chars, like & and +

use strict;
use warnings;

#my $browser = 'firefox';
my $browser = 'defaultbrowser';

my $primary = qx/ xsel -p -o /;

exit 0 if (not $primary);

# Trim leading and traling whitespaces.
$primary =~ s/^\s+//;
$primary =~ s/\s+$//;

# Strip leading and traling < >.
$primary =~ s/^<(.*)>$/$1/;

my $link;
if ($primary !~ m/^(http|https):\/\//) {
    $link = "https://encrypted.google.com/search?q=" . $primary;
} else {
    $link = $primary;
}

system($browser, '--new-tab', $link);
