#!/usr/bin/env perl

use strict;
use warnings;

use URI::Encode;
my $encoder = URI::Encode->new();

#my $browser = 'firefox';
my $browser = 'defaultbrowser';

my $primary = qx/ xsel -p -o /;

exit 0 if (not $primary);

# Trim leading and traling whitespaces.
$primary =~ s/^\s+//;
$primary =~ s/\s+$//;

# Strip leading and traling < >.
$primary =~ s/^<(.*)>$/$1/;

my $encoded = $encoder->encode($primary, { encode_reserved => 1});

my $link;
if ($encoded !~ m/^(http|https):\/\//) {
    $link = "https://encrypted.google.com/search?q=" . $encoded;
} else {
    $link = $encoded;
}

system($browser, '--new-tab', $link);
