#!/usr/bin/env perl

# Preload first $preload_up_to megabytes of specified files into page caches.

use strict;
use warnings;

my $fh;
my $content;

my $max_processes = 2;
my $preload_up_to = 15;

sub preload_file {
    printf("Preloading %s ...\n", $_);
    open($fh, "<", $_) or die;
    read($fh, $content, 1024*1024*${preload_up_to}) or die;
    undef($content);
    close($fh) or die;
}

my $fm_is_avalabile = eval {
    require Parallel::ForkManager;
    Parallel::ForkManager->import;
    1
};

if ($fm_is_avalabile) {
    my $fm = new Parallel::ForkManager($max_processes);

    for (@ARGV) {
        next if not -f;
        next if not -s;

        $fm->start and next;

        preload_file($_);
        
        $fm->finish;
    }
} else {
    for (@ARGV) {
        next if not -f;
        next if not -s;

        preload_file($_);
    }
};
