#!/bin/bash

# Simple (and rather limited) script to sync local directory to another (remote) location
# keeping up to 3 old version on destination with hardlink-based snapshots.
#
# First argument is source directory.
# Second argument is destination, local or remote.
# Any additional argument is passed to rsync as option.
#
# Usage:
#   rsnapdir <source_dir> [remote:]<destination_dir>
#   rsnapdir ~/music user@host:dropzone/music
#   rsnapdir ~/backups foo@bar:backups --bwlimit 500
#   rsnapdir . /media/sdb1/home-backup
#
# Limitations:
#   - Script will refuse to work with destination that include white chars.
#   - Due to usage of `readlink -f` the script will not work on MacOS as-is.
#   - To set custom ssh port, one needs to configure it in ~/.ssh/config.
#
# To be added:
#   - support for remote source
#   - Use single ssh connection with ControlMaster
#   - Support for non-default ssh options, like port.

set -e

eerror() {
    echo "[ERROR] >>> $*" >&2
}

einfo() {
    echo "[INFO] >>> $*" >&2
}

edie() {
    eerror "$*"
    exit 1
}

run() {
    einfo "Running $*"
    "$@"
}

dst_run() {
    if [ "${remote}" ]; then
        run ssh "${remote}" "$@"
    else
        run "$@"
    fi
}

snapshot_directory() {
    dir="$1"

    if dst_run test -d "${dir}-snapshot-5"; then
        dst_run rm -rf "${dir}-snapshot-5"
    fi

    if dst_run test -d "${dir}-snapshot-4"; then
        dst_run mv "${dir}-snapshot-4" "${dir}-snapshot-5"
    fi

    if dst_run test -d "${dir}-snapshot-3"; then
        dst_run mv "${dir}-snapshot-3" "${dir}-snapshot-4"
    fi

    if dst_run test -d "${dir}-snapshot-2"; then
        dst_run mv "${dir}-snapshot-2" "${dir}-snapshot-3"
    fi

    if dst_run test -d "${dir}-snapshot-1"; then
        dst_run mv "${dir}-snapshot-1" "${dir}-snapshot-2"
    fi

    if dst_run test -d "${dir}"; then
        dst_run cp -al "${dir}" "${dir}-snapshot-1"
    fi
}

if ! [ "$#" -ge 2 ]; then
    edie "Wrong amount of arguments."
fi

unset remote

src="$1"
src="$(run readlink -f "${src}")"

dst="$2"

case "${dst}" in
    *':'*)
        remote="${dst%%:*}"
    ;;
esac

dst="${dst#*:}"

if ! [ "${src}" ]; then
    edie 'Source needs to be set'
fi

if [[ "${dst}" =~ ^(\.\.*|[./]+)$ ]]; then
    edie "Named destination needed"
fi

if ! [ "${dst}" ]; then
    edie 'Destination has not been set.'
fi

if [[ "${dst}" =~ [[:blank:]] ]]; then
    # Not worth the effort to support it when $remote is set.
    edie 'White chars in destination are not supported'
fi

while [[ "${dst}" =~ /$ ]]; do
    dst="${dst%/}"
done

if ! [ -d "${src}" ]; then
    edie "Source needs to be directory"
fi

shift 2

snapshot_directory "${dst}"
dst_run mkdir -p "${dst}"
run rsync "$@" --hard-links --delete --partial --numeric-ids -a --progress "${src}/" "${remote}${remote:+:}${dst}/"
