#!/usr/bin/awk -f
BEGIN {
	cmd = "synclient -l"
	while ( cmd | getline > 0 ) {
		if ($1 == "TouchpadOff") {
			if ($3 == "1" ) {
				system("synclient TouchpadOff=0")
			} else if ($3 == "0") {
				system("synclient TouchpadOff=1")
			} else {
				exit 1
			}
			exit
		}
	}
	close(cmd)
}
