#!/bin/sh
# Toggle touchpad.

status="$(synclient -l | mawk '$1 == "TouchpadOff" { print $3 }')"

if [ "$status" = "1" ]; then
	synclient TouchpadOff=0
elif [ "$status" = "0" ]; then
	synclient TouchpadOff=1
else
	echo "The fuck is this? Status = '${status}'".
	exit 1
fi
