#!/bin/dash
# Volume control.

step='3'

up() {
	amixer -q set Master ${step}+ unmute
}

down() {
	amixer -q set Master ${step}- unmute
}

mute() {
	amixer -q set Master mute
}

case $1 in
	up|down|mute)
		$1
	;;
	*)
		echo "Zjebales." && exit 1
	;;
esac
